language: node_js
node_js:
  - "10"
jobs:
  include:
    - script: npm install
    - script: npm test
    - script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        token: $GITHUB_OAUTH_TOKEN
        local_dir: ./dist
        keep_history: true
        edge: true
        on:
          tags: true
